In [ ]:
import modern_robotics as mr 
import numpy as np 
import milestone_func as ms_func
import matplotlib.pyplot as plt
from milestone_config import *

In [57]:
Xd = np.array([[0, 0, 1, .5], 
               [0, 1, 0, 0], 
               [-1, 0, 0, .5], 
               [0, 0, 0, 1]])
Xd_next = np.array([[0, 0, 1, .6], 
                   [0, 1, 0, 0], 
                   [-1, 0, 0, .3], 
                   [0, 0, 0, 1]])
X = np.array([[.17, 0, .985, .387], 
              [0, 1, 0, 0],
              [-.985, 0, .17, .57], 
              [0, 0, 0, 1]])
Kp = np.eye(6)
Ki = np.zeros((6, 6))
dt = .01

In [ ]:
robot_config = np.array([0, 0, 0, 0, 0, .2, -1.6, 0])
Jbase = 

In [55]:
def Jacobian_EE():
    """
    Je = [base (4), arm (5)]
    """
    return

In [47]:
Vd =  mr.se3ToVec(mr.MatrixLog6(mr.TransInv(Xd) @ Xd_next)/dt)
Vd

array([ 0.,  0.,  0., 20.,  0., 10.])

In [48]:
Adj = mr.Adjoint(mr.TransInv(X) @ Xd)
Adj @ Vd

array([ 0.  ,  0.  ,  0.  , 21.4 ,  0.  ,  6.45])

In [49]:
X_err = mr.se3ToVec(mr.MatrixLog6(mr.TransInv(X) @ Xd))
X_err

array([0.        , 0.17085513, 0.        , 0.07945351, 0.        ,
       0.10669436])

In [50]:
X_err_int = X_err + X_err*dt
Adj @ Vd + Kp @ X_err + Ki @ X_err_int

array([ 0.        ,  0.17085513,  0.        , 21.47945351,  0.        ,
        6.55669436])

In [51]:
def FeedbackControl(X, Xd, Xd_next, Kp, Ki, dt):
    Vd =  mr.se3ToVec(mr.MatrixLog6(mr.TransInv(Xd) @ Xd_next)/dt)
    Adj = mr.Adjoint(mr.TransInv(X) @ Xd)
    X_err = mr.se3ToVec(mr.MatrixLog6(mr.TransInv(X) @ Xd))
    X_err_int = X_err + X_err*dt
    return Adj @ Vd + Kp @ X_err + Ki @ X_err_int